// Banco de itens padrão (semente inicial). Cada item tem { nome, metric }.
// metric é uma nota de referência pré-pesquisada e embutida estaticamente
// (nada é buscado em runtime — o app é 100% offline).
//
// - jogos: Metacritic (0-100)
// - series / filmes: nota IMDb (0-10) — auditada e corrigida contra o IMDb real em 2026-09-20
// - atletas: "Índice de Lendas" (0-100), estimativa curada por título/recorde/
//   reconhecimento — não é uma fonte oficial única, já que não existe uma
//   métrica cross-esporte padronizada.
//
// DADOS_VERSAO: suba este número sempre que adicionar/corrigir itens ou temas aqui.
// O app compara com a versão salva no localStorage e mescla as novidades no banco
// do jogador (sem apagar o que ele adicionou manualmente).
// v4 (2026-09-20): +tema "desenhos" (desenhos animados/TV infantil que marcaram
// gerações no Brasil — TV Globinho, TV Cultura, SBT, Cartoon Network/Nickelodeon
// Brasil), notas IMDb pesquisadas e embutidas estaticamente.
const DADOS_VERSAO = 4;

const TEMAS_META = {
  jogos: { label: "Jogos", icon: "🎮", metricLabel: "Metacritic", metricMax: 100 },
  atletas: { label: "Melhores Atletas", icon: "🏅", metricLabel: "Índice de Lendas (estimativa)", metricMax: 100 },
  series: { label: "Melhores Séries", icon: "📺", metricLabel: "Nota IMDb", metricMax: 10 },
  filmes: { label: "Melhores Filmes", icon: "🎬", metricLabel: "Nota IMDb", metricMax: 10 },
  paises: { label: "Países (IDH)", icon: "🌍", metricLabel: "IDH x100", metricMax: 100 },
  esportes: { label: "Esportes Mais Populares", icon: "⚽", metricLabel: "Índice de Popularidade (estimativa)", metricMax: 100 },
  albuns: { label: "Álbuns Mais Aclamados", icon: "💿", metricLabel: "Metacritic Music", metricMax: 100 },
  herois: { label: "Super-Heróis e Vilões", icon: "🦸", metricLabel: "Índice de Poder (estimativa)", metricMax: 100 },
  desenhos: { label: "Desenhos Animados", icon: "🖍️", metricLabel: "Nota IMDb", metricMax: 10 },
};

const DADOS_PADRAO = {
  jogos: [
    { nome: "The Legend of Zelda: Ocarina of Time", metric: 99 },
    { nome: "The Legend of Zelda: Breath of the Wild", metric: 97 },
    { nome: "Elden Ring", metric: 96 },
    { nome: "Red Dead Redemption 2", metric: 97 },
    { nome: "Grand Theft Auto V", metric: 97 },
    { nome: "The Witcher 3: Wild Hunt", metric: 92 },
    { nome: "God of War (2018)", metric: 94 },
    { nome: "God of War Ragnarök", metric: 94 },
    { nome: "Super Mario Odyssey", metric: 97 },
    { nome: "Super Mario Galaxy", metric: 97 },
    { nome: "Half-Life 2", metric: 96 },
    { nome: "Portal 2", metric: 95 },
    { nome: "The Last of Us", metric: 95 },
    { nome: "The Last of Us Part II", metric: 93 },
    { nome: "Hollow Knight", metric: 90 },
    { nome: "Celeste", metric: 92 },
    { nome: "Stardew Valley", metric: 89 },
    { nome: "Minecraft", metric: 93 },
    { nome: "Fortnite", metric: 79 },
    { nome: "Counter-Strike 2", metric: 81 },
    { nome: "Overwatch 2", metric: 79 },
    { nome: "Animal Crossing: New Horizons", metric: 90 },
    { nome: "EA Sports FC 24", metric: 79 },
    { nome: "Cyberpunk 2077", metric: 86 },
    { nome: "Hades", metric: 93 },
    { nome: "Terraria", metric: 83 },
    { nome: "The Elder Scrolls V: Skyrim", metric: 94 },
    { nome: "Fallout 4", metric: 84 },
    { nome: "Resident Evil 4 (Remake)", metric: 93 },
    { nome: "Marvel's Spider-Man 2", metric: 90 },
    { nome: "Horizon Zero Dawn", metric: 89 },
    { nome: "Sekiro: Shadows Die Twice", metric: 90 },
    { nome: "Bloodborne", metric: 92 },
    { nome: "Persona 5 Royal", metric: 95 },
    { nome: "Final Fantasy VII Remake", metric: 87 },
    { nome: "Street Fighter 6", metric: 92 },
    { nome: "Mortal Kombat 1", metric: 83 },
    { nome: "Rocket League", metric: 86 },
    { nome: "Apex Legends", metric: 88 },
    { nome: "World of Warcraft", metric: 92 },
    { nome: "Dota 2", metric: 90 },
    { nome: "Genshin Impact", metric: 84 },
    { nome: "It Takes Two", metric: 89 },
    { nome: "Baldur's Gate 3", metric: 96 },
    { nome: "Diablo IV", metric: 84 },
    { nome: "Portal", metric: 90 },
    { nome: "Journey", metric: 92 },
    { nome: "Undertale", metric: 92 },
    { nome: "Disco Elysium", metric: 91 },
    // --- expansão 2026-09-20 (+75) ---
    { nome: "Tony Hawk's Pro Skater 2", metric: 98 },
    { nome: "Grand Theft Auto IV", metric: 98 },
    { nome: "Halo: Combat Evolved", metric: 97 },
    { nome: "Metroid Prime", metric: 97 },
    { nome: "Mass Effect 2", metric: 96 },
    { nome: "BioShock", metric: 96 },
    { nome: "Uncharted 2: Among Thieves", metric: 96 },
    { nome: "The Legend of Zelda: Tears of the Kingdom", metric: 96 },
    { nome: "GoldenEye 007", metric: 96 },
    { nome: "Red Dead Redemption", metric: 95 },
    { nome: "Grand Theft Auto: San Andreas", metric: 95 },
    { nome: "Metal Gear Solid", metric: 94 },
    { nome: "Call of Duty 4: Modern Warfare", metric: 94 },
    { nome: "Astro Bot", metric: 94 },
    { nome: "God of War II", metric: 93 },
    { nome: "Super Smash Bros. Ultimate", metric: 93 },
    { nome: "Mario Kart 8 Deluxe", metric: 92 },
    { nome: "Chrono Trigger", metric: 92 },
    { nome: "Clair Obscur: Expedition 33", metric: 92 },
    { nome: "Hollow Knight: Silksong", metric: 90 },
    { nome: "Tetris Effect", metric: 89 },
    { nome: "Call of Duty: Black Ops", metric: 87 },
    { nome: "Sonic Mania", metric: 86 },
    { nome: "PlayerUnknown's Battlegrounds", metric: 86 },
    { nome: "FIFA 17", metric: 85 },
    { nome: "Among Us", metric: 85 },
    { nome: "Clash Royale", metric: 85 },
    { nome: "Destiny 2", metric: 85 },
    { nome: "Need for Speed: Most Wanted (2012)", metric: 84 },
    { nome: "Pokémon Legends: Arceus", metric: 83 },
    { nome: "Crash Team Racing Nitro-Fueled", metric: 83 },
    { nome: "Battlefield 6", metric: 83 },
    { nome: "Need for Speed: Underground 2", metric: 82 },
    { nome: "Mario Kart Wii", metric: 82 },
    { nome: "Far Cry 5", metric: 81 },
    { nome: "Fall Guys", metric: 81 },
    { nome: "Pokémon Sword", metric: 80 },
    { nome: "Assassin's Creed Valhalla", metric: 80 },
    { nome: "Crash Bandicoot N. Sane Trilogy", metric: 80 },
    { nome: "Angry Birds", metric: 80 },
    { nome: "Call of Duty: Warzone", metric: 79 },
    { nome: "Pro Evolution Soccer 2019", metric: 79 },
    { nome: "Candy Crush Saga", metric: 79 },
    { nome: "League of Legends", metric: 78 },
    { nome: "Clash of Clans", metric: 74 },
    { nome: "Far Cry 6", metric: 73 },
    { nome: "Dragon Ball Z: Kakarot", metric: 73 },
    { nome: "Pokémon Scarlet", metric: 72 },
    { nome: "Brawl Stars", metric: 72 },
    { nome: "Nintendo Switch Sports", metric: 72 },
    { nome: "Need for Speed Heat", metric: 72 },
    { nome: "No Man's Sky", metric: 71 },
    { nome: "Mass Effect: Andromeda", metric: 71 },
    { nome: "The Sims 4", metric: 70 },
    { nome: "Assassin's Creed Unity", metric: 70 },
    { nome: "Pokémon GO", metric: 69 },
    { nome: "Star Wars Battlefront II (2017)", metric: 68 },
    { nome: "Marvel's Avengers", metric: 67 },
    { nome: "Forspoken", metric: 64 },
    { nome: "Battlefield 2042", metric: 63 },
    { nome: "Concord", metric: 62 },
    { nome: "Suicide Squad: Kill the Justice League", metric: 60 },
    { nome: "Skull and Bones", metric: 59 },
    { nome: "Anthem", metric: 59 },
    { nome: "Redfall", metric: 56 },
    { nome: "Call of Duty: Modern Warfare III (2023)", metric: 56 },
    { nome: "Grand Theft Auto: The Trilogy – The Definitive Edition", metric: 54 },
    { nome: "Balan Wonderworld", metric: 51 },
    { nome: "Aliens: Colonial Marines", metric: 48 },
    { nome: "Sonic the Hedgehog (2006)", metric: 46 },
    { nome: "Fast & Furious Crossroads", metric: 35 },
    { nome: "eFootball 2022", metric: 34 },
    { nome: "The Lord of the Rings: Gollum", metric: 33 },
    { nome: "Ride to Hell: Retribution", metric: 19 },
    { nome: "Big Rigs: Over the Road Racing", metric: 6 },
  ],
  atletas: [
    { nome: "Pelé", metric: 98 },
    { nome: "Diego Maradona", metric: 96 },
    { nome: "Cristiano Ronaldo", metric: 97 },
    { nome: "Lionel Messi", metric: 99 },
    { nome: "Michael Jordan", metric: 99 },
    { nome: "LeBron James", metric: 97 },
    { nome: "Usain Bolt", metric: 97 },
    { nome: "Michael Phelps", metric: 98 },
    { nome: "Serena Williams", metric: 96 },
    { nome: "Roger Federer", metric: 95 },
    { nome: "Rafael Nadal", metric: 95 },
    { nome: "Novak Djokovic", metric: 97 },
    { nome: "Muhammad Ali", metric: 98 },
    { nome: "Tom Brady", metric: 95 },
    { nome: "Neymar", metric: 88 },
    { nome: "Ronaldinho Gaúcho", metric: 90 },
    { nome: "Kobe Bryant", metric: 95 },
    { nome: "Simone Biles", metric: 96 },
    { nome: "Allyson Felix", metric: 85 },
    { nome: "Tiger Woods", metric: 93 },
    { nome: "Ayrton Senna", metric: 96 },
    { nome: "Lewis Hamilton", metric: 95 },
    { nome: "Michael Schumacher", metric: 96 },
    { nome: "Wayne Gretzky", metric: 96 },
    { nome: "Babe Ruth", metric: 94 },
    { nome: "Kareem Abdul-Jabbar", metric: 92 },
    { nome: "Zinedine Zidane", metric: 92 },
    { nome: "Ronaldo Fenômeno", metric: 93 },
    { nome: "Gabriel Medina", metric: 82 },
    { nome: "Rebeca Andrade", metric: 85 },
    { nome: "Marta (futebol)", metric: 92 },
    { nome: "Shaquille O'Neal", metric: 91 },
    { nome: "Magic Johnson", metric: 93 },
    { nome: "Larry Bird", metric: 92 },
    { nome: "Vinícius Júnior", metric: 84 },
    { nome: "Kylian Mbappé", metric: 90 },
    { nome: "Erling Haaland", metric: 87 },
    { nome: "Stephen Curry", metric: 93 },
    { nome: "Giannis Antetokounmpo", metric: 91 },
    { nome: "Katie Ledecky", metric: 90 },
    { nome: "Eliud Kipchoge", metric: 88 },
    { nome: "Florence Griffith-Joyner", metric: 85 },
    { nome: "Jesse Owens", metric: 90 },
    { nome: "Pete Sampras", metric: 88 },
    { nome: "Sebastian Vettel", metric: 86 },
    { nome: "Nadia Comăneci", metric: 87 },
    { nome: "Carl Lewis", metric: 89 },
    // --- expansão 2026-09-20 (+75) ---
    { nome: "Johan Cruyff", metric: 94 },
    { nome: "Franz Beckenbauer", metric: 93 },
    { nome: "Garrincha", metric: 93 },
    { nome: "Romário", metric: 92 },
    { nome: "Zico", metric: 91 },
    { nome: "Rivaldo", metric: 88 },
    { nome: "Roberto Carlos", metric: 88 },
    { nome: "Kaká", metric: 87 },
    { nome: "Cafu", metric: 87 },
    { nome: "Sócrates", metric: 86 },
    { nome: "Falcão (futsal)", metric: 85 },
    { nome: "Wilt Chamberlain", metric: 93 },
    { nome: "Bill Russell", metric: 93 },
    { nome: "Oscar Schmidt", metric: 87 },
    { nome: "Hortência", metric: 80 },
    { nome: "Caitlin Clark", metric: 72 },
    { nome: "Steffi Graf", metric: 94 },
    { nome: "Martina Navratilova", metric: 93 },
    { nome: "Guga (Gustavo Kuerten)", metric: 88 },
    { nome: "Iga Świątek", metric: 84 },
    { nome: "Bia Haddad Maia", metric: 68 },
    { nome: "João Fonseca", metric: 62 },
    { nome: "Jim Thorpe", metric: 93 },
    { nome: "Maurren Maggi", metric: 76 },
    { nome: "Thiago Braz", metric: 70 },
    { nome: "Alison dos Santos (Piu)", metric: 70 },
    { nome: "Vanderlei Cordeiro de Lima", metric: 68 },
    { nome: "Cesar Cielo", metric: 82 },
    { nome: "Ana Marcela Cunha", metric: 80 },
    { nome: "Daiane dos Santos", metric: 76 },
    { nome: "Arthur Zanetti", metric: 74 },
    { nome: "Diego Hypólito", metric: 66 },
    { nome: "Max Verstappen", metric: 91 },
    { nome: "Nelson Piquet", metric: 89 },
    { nome: "Emerson Fittipaldi", metric: 86 },
    { nome: "Rubens Barrichello", metric: 74 },
    { nome: "Felipe Massa", metric: 70 },
    { nome: "Valentino Rossi", metric: 92 },
    { nome: "Sugar Ray Robinson", metric: 94 },
    { nome: "Mike Tyson", metric: 91 },
    { nome: "Éder Jofre", metric: 86 },
    { nome: "Popó (Acelino Freitas)", metric: 81 },
    { nome: "Anderson Silva", metric: 88 },
    { nome: "Amanda Nunes", metric: 85 },
    { nome: "José Aldo", metric: 82 },
    { nome: "Conor McGregor", metric: 82 },
    { nome: "Alex Poatan", metric: 78 },
    { nome: "Charles do Bronx", metric: 77 },
    { nome: "Teddy Riner", metric: 91 },
    { nome: "Rafaela Silva", metric: 75 },
    { nome: "Giba", metric: 84 },
    { nome: "Bernardinho", metric: 85 },
    { nome: "Sheilla", metric: 80 },
    { nome: "Serginho (vôlei)", metric: 78 },
    { nome: "Fabi (vôlei)", metric: 73 },
    { nome: "Adriana Behar", metric: 75 },
    { nome: "Jack Nicklaus", metric: 94 },
    { nome: "Eddy Merckx", metric: 94 },
    { nome: "Lance Armstrong", metric: 70 },
    { nome: "Kelly Slater", metric: 93 },
    { nome: "Italo Ferreira", metric: 80 },
    { nome: "Tony Hawk", metric: 88 },
    { nome: "Rayssa Leal", metric: 79 },
    { nome: "Patrick Mahomes", metric: 90 },
    { nome: "Shohei Ohtani", metric: 90 },
    { nome: "Garry Kasparov", metric: 93 },
    { nome: "Magnus Carlsen", metric: 92 },
    { nome: "Sachin Tendulkar", metric: 93 },
    { nome: "Isaquias Queiroz", metric: 80 },
    { nome: "Robert Scheidt", metric: 84 },
    { nome: "Torben Grael", metric: 80 },
    { nome: "Hugo Calderano", metric: 77 },
    { nome: "Faker (Lee Sang-hyeok)", metric: 85 },
    { nome: "FalleN (Gabriel Toledo)", metric: 76 },
    { nome: "Mikaela Shiffrin", metric: 88 },
  ],
  series: [
    // --- base original, notas auditadas e corrigidas contra o IMDb real em 2026-09-20 ---
    { nome: "Breaking Bad", metric: 9.5 },
    { nome: "Game of Thrones", metric: 9.2 },
    { nome: "The Wire", metric: 9.3 },
    { nome: "The Sopranos", metric: 9.2 },
    { nome: "Friends", metric: 8.8 },
    { nome: "Stranger Things", metric: 8.6 },
    { nome: "The Office (US)", metric: 9.0 },
    { nome: "Chernobyl", metric: 9.3 },
    { nome: "The Crown", metric: 8.6 },
    { nome: "Better Call Saul", metric: 9.0 },
    { nome: "Succession", metric: 8.8 },
    { nome: "The Last of Us (série)", metric: 8.4 },
    { nome: "House M.D.", metric: 8.7 },
    { nome: "Lost", metric: 8.3 },
    { nome: "Dexter", metric: 8.6 },
    { nome: "Peaky Blinders", metric: 8.7 },
    { nome: "Narcos", metric: 8.7 },
    { nome: "Sherlock", metric: 9.0 },
    { nome: "True Detective", metric: 8.8 },
    { nome: "Fargo", metric: 8.8 },
    { nome: "Westworld", metric: 8.4 },
    { nome: "Black Mirror", metric: 8.7 },
    { nome: "The Mandalorian", metric: 8.6 },
    { nome: "Band of Brothers", metric: 9.4 },
    { nome: "Grey's Anatomy", metric: 7.6 },
    { nome: "How I Met Your Mother", metric: 8.3 },
    { nome: "Brooklyn Nine-Nine", metric: 8.4 },
    { nome: "Rick and Morty", metric: 9.0 },
    { nome: "The Big Bang Theory", metric: 8.1 },
    { nome: "La Casa de Papel", metric: 8.2 },
    { nome: "Ozark", metric: 8.4 },
    { nome: "Mindhunter", metric: 8.6 },
    { nome: "The Boys", metric: 8.5 },
    { nome: "Yellowstone", metric: 8.6 },
    { nome: "Round 6 (Squid Game)", metric: 7.9 },
    { nome: "Wandinha (Wednesday)", metric: 8.0 },
    { nome: "The Handmaid's Tale", metric: 8.3 },
    { nome: "Twin Peaks", metric: 8.7 },
    { nome: "Seinfeld", metric: 8.8 },
    { nome: "Cheers", metric: 8.0 },
    { nome: "The Walking Dead", metric: 8.1 },
    { nome: "Vikings", metric: 8.5 },
    { nome: "Downton Abbey", metric: 8.7 },
    { nome: "This Is Us", metric: 8.7 },
    { nome: "Community", metric: 8.5 },
    { nome: "Avatar: A Lenda de Aang", metric: 9.3 },
    { nome: "Prison Break", metric: 8.3 },
    { nome: "Dark", metric: 8.7 },
    { nome: "Attack on Titan", metric: 9.1 },
    // --- expansão: nota alta (8+), pra variar o gênero/origem ---
    { nome: "Reply 1988", metric: 9.0 },
    { nome: "Hospital Playlist", metric: 8.7 },
    { nome: "Pousando no Amor", metric: 8.8 },
    { nome: "Fullmetal Alchemist: Brotherhood", metric: 9.1 },
    { nome: "Death Note", metric: 8.9 },
    { nome: "One Piece", metric: 9.0 },
    { nome: "Demon Slayer: Kimetsu no Yaiba", metric: 8.5 },
    { nome: "It's Always Sunny in Philadelphia", metric: 8.8 },
    { nome: "Parks and Recreation", metric: 8.6 },
    { nome: "Ted Lasso", metric: 8.7 },
    { nome: "Fleabag", metric: 8.7 },
    { nome: "Nosso Planeta", metric: 9.2 },
    { nome: "Arremesso Final", metric: 9.0 },
    { nome: "O Urso", metric: 8.5 },
    { nome: "Ruptura", metric: 8.6 },
    { nome: "Shōgun", metric: 8.6 },
    { nome: "Arquivo X", metric: 8.6 },
    { nome: "Sob Pressão", metric: 8.6 },
    { nome: "Pantanal (2022)", metric: 8.2 },
    // --- expansão: nota média (6.5-7.4), pra dar surpresa ---
    { nome: "Two and a Half Men", metric: 7.1 },
    { nome: "Pretty Little Liars", metric: 7.3 },
    { nome: "13 Reasons Why", metric: 7.4 },
    { nome: "Glee", metric: 6.8 },
    { nome: "Girl Meets World", metric: 7.0 },
    { nome: "iCarly", metric: 6.8 },
    { nome: "Victorious", metric: 7.0 },
    { nome: "Sabrina, a Aprendiz de Feiticeira", metric: 6.7 },
    { nome: "Três É Demais", metric: 6.8 },
    { nome: "Fuller House", metric: 6.7 },
    { nome: "The Flash", metric: 7.4 },
    { nome: "Charmed (1998)", metric: 7.2 },
    { nome: "Fear the Walking Dead", metric: 6.7 },
    { nome: "Titans", metric: 7.4 },
    { nome: "Beverly Hills, 90210", metric: 6.6 },
    { nome: "Xena: A Princesa Guerreira", metric: 6.8 },
    { nome: "Power Rangers (1993)", metric: 6.6 },
    { nome: "Dragon Ball GT", metric: 6.8 },
    { nome: "Beyblade", metric: 6.9 },
    { nome: "Digimon: A Batalha dos Encouraçados", metric: 7.4 },
    { nome: "Zack e Cody: Gêmeos em Ação", metric: 6.7 },
    { nome: "Carrossel", metric: 6.9 },
    { nome: "Rebelde", metric: 7.0 },
    { nome: "Sintonia", metric: 6.8 },
    { nome: "Dawson's Creek", metric: 6.8 },
    { nome: "Barrados no Baile", metric: 7.1 },
    { nome: "That's So Raven", metric: 6.7 },
    { nome: "Big Time Rush", metric: 6.6 },
    { nome: "H2O: Just Add Water", metric: 7.3 },
    { nome: "Com a Corda Toda", metric: 7.1 },
    { nome: "Lendas do Amanhã", metric: 6.7 },
    { nome: "Kim Possible", metric: 7.3 },
    { nome: "My Wife and Kids", metric: 7.0 },
    { nome: "George Lopez", metric: 6.9 },
    { nome: "Duas Garotas em Apuros", metric: 6.7 },
    { nome: "Mike & Molly", metric: 6.6 },
    { nome: "Pretty Little Liars: The Perfectionists", metric: 6.8 },
    { nome: "Shadowhunters", metric: 6.5 },
    // --- expansão: nota baixa/mediana (4.5-6.4), pra surpresa de verdade ---
    { nome: "Riverdale", metric: 6.4 },
    { nome: "Gossip Girl (2021)", metric: 5.4 },
    { nome: "The Witcher: Blood Origin", metric: 5.0 },
    { nome: "Inumanos", metric: 4.9 },
    { nome: "Charmed (2018)", metric: 4.8 },
    { nome: "And Just Like That...", metric: 5.6 },
    { nome: "Sex/Life", metric: 5.6 },
    { nome: "Cursed", metric: 6.0 },
    { nome: "Supergirl", metric: 6.2 },
    { nome: "Violetta", metric: 5.6 },
    { nome: "Grease: Rise of the Pink Ladies", metric: 6.1 },
    { nome: "Como Eu Conheci Seu Pai", metric: 5.7 },
    { nome: "Joey", metric: 6.0 },
    { nome: "Too Hot to Handle: Mão no Bolso!", metric: 4.8 },
    { nome: "Love Is Blind", metric: 6.2 },
    { nome: "90 Dias Para Casar", metric: 6.4 },
    { nome: "America's Next Top Model", metric: 5.6 },
    { nome: "Big Brother (EUA)", metric: 5.6 },
    { nome: "The Real Housewives of Beverly Hills", metric: 5.7 },
    { nome: "A Fazenda", metric: 5.0 },
    { nome: "Chiquititas (2013)", metric: 6.0 },
    { nome: "Punho de Ferro", metric: 6.4 },
    { nome: "90210", metric: 6.2 },
    { nome: "Roswell, New Mexico", metric: 6.4 },
    // --- expansão 2026-09-20 (+50) ---
    { nome: "Vale Tudo (1988)", metric: 9.1 },
    { nome: "Avenida Brasil", metric: 8.4 },
    { nome: "O Clone", metric: 8.1 },
    { nome: "Cidade dos Homens", metric: 8.2 },
    { nome: "Os Normais", metric: 8.3 },
    { nome: "Chaves", metric: 8.7 },
    { nome: "Chapolin", metric: 8.5 },
    { nome: "Cangaço Novo", metric: 8.2 },
    { nome: "Os Simpsons", metric: 8.6 },
    { nome: "South Park", metric: 8.7 },
    { nome: "Hora de Aventura", metric: 8.7 },
    { nome: "Gravity Falls", metric: 8.9 },
    { nome: "Dragon Ball Z", metric: 8.8 },
    { nome: "Hunter x Hunter (2011)", metric: 9.0 },
    { nome: "Cowboy Bebop (1998)", metric: 8.9 },
    { nome: "Arcane", metric: 9.0 },
    { nome: "Invencível", metric: 8.7 },
    { nome: "A Casa do Dragão", metric: 8.3 },
    { nome: "Adolescência", metric: 8.1 },
    { nome: "Uma Advogada Extraordinária", metric: 8.5 },
    { nome: "Goblin", metric: 8.5 },
    { nome: "A Grande Família", metric: 7.8 },
    { nome: "Todo Mundo Odeia o Chris", metric: 7.6 },
    { nome: "Verdades Secretas", metric: 7.8 },
    { nome: "Bom Dia, Verônica", metric: 7.4 },
    { nome: "3%", metric: 7.2 },
    { nome: "Pokémon", metric: 7.6 },
    { nome: "Bebê Rena", metric: 7.7 },
    { nome: "Bridgerton", metric: 7.5 },
    { nome: "Emily em Paris", metric: 6.8 },
    { nome: "Você (You)", metric: 7.6 },
    { nome: "Elite", metric: 7.1 },
    { nome: "The Witcher", metric: 7.8 },
    { nome: "WandaVision", metric: 7.9 },
    { nome: "O Senhor dos Anéis: Os Anéis de Poder", metric: 6.8 },
    { nome: "Cowboy Bebop (2021)", metric: 6.7 },
    { nome: "Avatar: O Último Mestre do Ar (2024)", metric: 7.1 },
    { nome: "Alice in Borderland", metric: 7.8 },
    { nome: "Velma", metric: 1.7 },
    { nome: "The Idol", metric: 4.4 },
    { nome: "Malhação", metric: 4.9 },
    { nome: "Invasão Secreta", metric: 5.8 },
    { nome: "Ms. Marvel", metric: 6.2 },
    { nome: "Batwoman", metric: 3.6 },
    { nome: "Keeping Up with the Kardashians", metric: 2.9 },
    { nome: "Resident Evil (2022)", metric: 4.2 },
    { nome: "Big Brother Brasil", metric: 4.3 },
    { nome: "Teletubbies", metric: 3.9 },
    { nome: "Mulher-Hulk: Defensora de Heróis", metric: 5.2 },
    { nome: "Zorra Total", metric: 3.0 },
  ],
  filmes: [
    // --- base original, notas auditadas e corrigidas contra o IMDb real em 2026-09-20 ---
    { nome: "O Poderoso Chefão", metric: 9.2 },
    { nome: "O Poderoso Chefão II", metric: 9.0 },
    { nome: "Pulp Fiction", metric: 8.9 },
    { nome: "Clube da Luta", metric: 8.8 },
    { nome: "Cidade de Deus", metric: 8.6 },
    { nome: "O Senhor dos Anéis: O Retorno do Rei", metric: 9.0 },
    { nome: "Star Wars: Episódio IV", metric: 8.6 },
    { nome: "Matrix", metric: 8.7 },
    { nome: "Interestelar", metric: 8.7 },
    { nome: "A Origem", metric: 8.8 },
    { nome: "Coringa", metric: 8.3 },
    { nome: "Vingadores: Ultimato", metric: 8.4 },
    { nome: "Parasita", metric: 8.5 },
    { nome: "Cinema Paradiso", metric: 8.5 },
    { nome: "Forrest Gump", metric: 8.8 },
    { nome: "Um Sonho de Liberdade", metric: 9.3 },
    { nome: "O Silêncio dos Inocentes", metric: 8.6 },
    { nome: "Pantera Negra", metric: 7.3 },
    { nome: "Titanic", metric: 7.9 },
    { nome: "Gladiador", metric: 8.5 },
    { nome: "Batman: O Cavaleiro das Trevas", metric: 9.1 },
    { nome: "Whiplash", metric: 8.5 },
    { nome: "La La Land", metric: 8.0 },
    { nome: "Coração Valente", metric: 8.3 },
    { nome: "De Volta para o Futuro", metric: 8.5 },
    { nome: "Jurassic Park", metric: 8.2 },
    { nome: "Tubarão", metric: 8.1 },
    { nome: "E.T. - O Extraterrestre", metric: 7.9 },
    { nome: "Rocky", metric: 8.1 },
    { nome: "Scarface", metric: 8.3 },
    { nome: "Os Infiltrados", metric: 8.5 },
    { nome: "Django Livre", metric: 8.5 },
    { nome: "Bastardos Inglórios", metric: 8.4 },
    { nome: "Kill Bill: Vol. 1", metric: 8.2 },
    { nome: "A Lista de Schindler", metric: 9.0 },
    { nome: "Amadeus", metric: 8.4 },
    { nome: "Casablanca", metric: 8.5 },
    { nome: "Psicose", metric: 8.5 },
    { nome: "Apocalypse Now", metric: 8.4 },
    { nome: "Taxi Driver", metric: 8.2 },
    { nome: "Bacurau", metric: 7.3 },
    { nome: "Central do Brasil", metric: 8.0 },
    { nome: "Tropa de Elite", metric: 8.0 },
    { nome: "Cidadão Kane", metric: 8.2 },
    { nome: "Snatch: Porcos e Diamantes", metric: 8.2 },
    { nome: "Trainspotting", metric: 8.1 },
    { nome: "Homem-Aranha: Através do Aranhaverso", metric: 8.5 },
    // --- expansão: nota alta (7.5+), pra variar gênero/época ---
    { nome: "Toy Story", metric: 8.3 },
    { nome: "WALL-E", metric: 8.4 },
    { nome: "O Rei Leão (1994)", metric: 8.5 },
    { nome: "A Viagem de Chihiro", metric: 8.6 },
    { nome: "Mad Max: Estrada da Fúria", metric: 8.1 },
    { nome: "Top Gun: Maverick", metric: 8.2 },
    { nome: "Indiana Jones e os Caçadores da Arca Perdida", metric: 8.4 },
    { nome: "Duro de Matar", metric: 8.2 },
    { nome: "O Exorcista", metric: 8.1 },
    { nome: "O Iluminado", metric: 8.4 },
    { nome: "Alien, o Oitavo Passageiro", metric: 8.5 },
    { nome: "Corra!", metric: 7.6 },
    { nome: "Feitiço do Tempo", metric: 8.0 },
    { nome: "Se Beber, Não Case", metric: 7.7 },
    { nome: "O Auto da Compadecida", metric: 8.6 },
    { nome: "Tropa de Elite 2: O Inimigo Agora é Outro", metric: 8.0 },
    { nome: "Um Estranho no Ninho", metric: 8.7 },
    { nome: "Doze Homens e uma Sentença", metric: 9.0 },
    // --- expansão: nota média (6.5-7.4), pra dar surpresa ---
    { nome: "Homem de Ferro 2", metric: 6.9 },
    { nome: "Homem de Ferro 3", metric: 7.1 },
    { nome: "Doutor Estranho no Multiverso da Loucura", metric: 6.8 },
    { nome: "Vingadores: Era de Ultron", metric: 7.3 },
    { nome: "X-Men: Apocalipse", metric: 6.8 },
    { nome: "Thor: O Mundo Sombrio", metric: 6.7 },
    { nome: "Venom", metric: 6.6 },
    { nome: "Pantera Negra: Wakanda Para Sempre", metric: 6.6 },
    { nome: "Capitã Marvel", metric: 6.7 },
    { nome: "Shazam!", metric: 7.0 },
    { nome: "Aquaman", metric: 6.8 },
    { nome: "Velozes & Furiosos 5: Operação Rio", metric: 7.3 },
    { nome: "Velozes & Furiosos 6", metric: 7.0 },
    { nome: "Velozes & Furiosos 7", metric: 7.1 },
    { nome: "Velozes & Furiosos 8", metric: 6.6 },
    { nome: "Homem-Aranha: Longe de Casa", metric: 7.3 },
    { nome: "King Kong (2005)", metric: 7.2 },
    { nome: "A Bela e a Fera (2017)", metric: 7.1 },
    { nome: "Aladdin (2019)", metric: 6.9 },
    { nome: "O Rei Leão (2019)", metric: 6.8 },
    { nome: "O Livro da Selva (2016)", metric: 7.3 },
    { nome: "Cinderela (2015)", metric: 6.9 },
    { nome: "Divergente", metric: 6.6 },
    { nome: "Jogos Vorazes: A Esperança – Parte 1", metric: 6.6 },
    { nome: "Jogos Vorazes: A Esperança – Parte 2", metric: 6.6 },
    { nome: "Se Beber, Não Case! Parte II", metric: 6.5 },
    { nome: "A Proposta", metric: 6.8 },
    { nome: "Como Eu Era Antes de Você", metric: 7.4 },
    { nome: "O Diabo Veste Prada", metric: 7.0 },
    { nome: "Uma Linda Mulher", metric: 7.1 },
    { nome: "Duro de Matar 2", metric: 7.2 },
    { nome: "Duro de Matar 4.0", metric: 7.1 },
    { nome: "Um Duende em Nova York", metric: 7.1 },
    { nome: "O Amor Não Tira Férias", metric: 7.0 },
    { nome: "Halloween (2018)", metric: 6.5 },
    { nome: "Jogos Mortais 2", metric: 6.6 },
    { nome: "It: Capítulo 2", metric: 6.5 },
    { nome: "Sobrenatural: Capítulo 2", metric: 6.6 },
    // --- expansão: nota baixa/mediana (4.5-6.4), pra surpresa de verdade ---
    { nome: "Homem-Aranha 3", metric: 6.3 },
    { nome: "Velozes e Furiosos: Desafio em Tóquio", metric: 6.1 },
    { nome: "Alien vs Predador", metric: 5.7 },
    { nome: "Alien vs. Predador 2", metric: 4.6 },
    { nome: "Crepúsculo", metric: 5.4 },
    { nome: "Lua Nova", metric: 4.8 },
    { nome: "50 Tons Mais Escuros", metric: 4.6 },
    { nome: "Esquadrão Suicida", metric: 5.9 },
    { nome: "Liga da Justiça", metric: 6.0 },
    { nome: "A Série Divergente: Convergente", metric: 5.7 },
    { nome: "A Múmia (2017)", metric: 5.4 },
    { nome: "Gente Grande 2", metric: 5.4 },
    { nome: "Independence Day: O Ressurgimento", metric: 5.2 },
    { nome: "Godzilla (1998)", metric: 5.5 },
    { nome: "O Rei Escorpião", metric: 5.5 },
    { nome: "Assassin's Creed", metric: 5.6 },
    { nome: "Max Payne", metric: 5.3 },
    { nome: "Batman Eternamente", metric: 5.4 },
    { nome: "Como o Grinch Roubou o Natal (2000)", metric: 6.4 },
    { nome: "Titio Noel", metric: 5.7 },
    { nome: "Transformers: O Último Cavaleiro", metric: 5.2 },
    { nome: "G.I. Joe: Retaliação", metric: 5.7 },
    { nome: "X-Men: Fênix Negra", metric: 5.7 },
    { nome: "Mulher-Maravilha 1984", metric: 5.3 },
    // --- expansão 2026-09-20 (+50) ---
    { nome: "Ainda Estou Aqui", metric: 8.1 },
    { nome: "O Pagador de Promessas", metric: 8.3 },
    { nome: "Que Horas Ela Volta?", metric: 7.8 },
    { nome: "Pixote: A Lei do Mais Fraco", metric: 7.9 },
    { nome: "Shrek", metric: 7.9 },
    { nome: "Procurando Nemo", metric: 8.2 },
    { nome: "Up: Altas Aventuras", metric: 8.3 },
    { nome: "Divertida Mente", metric: 8.1 },
    { nome: "Viva: A Vida é uma Festa", metric: 8.4 },
    { nome: "Os Incríveis", metric: 8.0 },
    { nome: "Ratatouille", metric: 8.1 },
    { nome: "O Exterminador do Futuro 2: O Julgamento Final", metric: 8.6 },
    { nome: "Piratas do Caribe: A Maldição do Pérola Negra", metric: 8.1 },
    { nome: "Harry Potter e as Relíquias da Morte – Parte 2", metric: 8.1 },
    { nome: "Deadpool", metric: 8.0 },
    { nome: "Logan", metric: 8.1 },
    { nome: "Oppenheimer", metric: 8.2 },
    { nome: "Duna: Parte Dois", metric: 8.4 },
    { nome: "Homem de Ferro", metric: 7.9 },
    { nome: "John Wick", metric: 7.5 },
    { nome: "Minha Mãe é uma Peça", metric: 6.9 },
    { nome: "Aquarius", metric: 7.4 },
    { nome: "Meu Nome Não é Johnny", metric: 7.2 },
    { nome: "2 Filhos de Francisco", metric: 6.9 },
    { nome: "Turma da Mônica: Laços", metric: 7.1 },
    { nome: "Frozen: Uma Aventura Congelante", metric: 7.4 },
    { nome: "Rio", metric: 6.9 },
    { nome: "Madagascar", metric: 7.0 },
    { nome: "Hereditário", metric: 7.3 },
    { nome: "Matrix Reloaded", metric: 7.2 },
    { nome: "Thor", metric: 7.0 },
    { nome: "Barbie", metric: 6.8 },
    { nome: "Star Wars: Episódio I – A Ameaça Fantasma", metric: 6.5 },
    { nome: "Dona Flor e Seus Dois Maridos (1976)", metric: 6.9 },
    { nome: "Emoji: O Filme", metric: 3.5 },
    { nome: "Cats (2019)", metric: 2.8 },
    { nome: "Dragonball Evolution", metric: 2.5 },
    { nome: "Morbius", metric: 5.1 },
    { nome: "Batman & Robin", metric: 3.8 },
    { nome: "Mulher-Gato", metric: 3.5 },
    { nome: "Sharknado", metric: 3.3 },
    { nome: "Cilada.com", metric: 5.2 },
    { nome: "50 Tons de Liberdade", metric: 4.6 },
    { nome: "After", metric: 5.3 },
    { nome: "Os Farofeiros", metric: 6.0 },
    { nome: "Matrix Resurrections", metric: 5.6 },
    { nome: "Até que a Sorte nos Separe", metric: 5.6 },
    { nome: "O Auto da Compadecida 2", metric: 6.1 },
    { nome: "Thor: Amor e Trovão", metric: 6.1 },
    { nome: "Batman vs Superman: A Origem da Justiça", metric: 6.4 },
  ],
  paises: [
    // IDH (Índice de Desenvolvimento Humano) x100, fonte: Relatório de Desenvolvimento Humano PNUD/ONU
    { nome: "Islândia", metric: 97.2 },
    { nome: "Noruega", metric: 97.0 },
    { nome: "Suíça", metric: 97.0 },
    { nome: "Alemanha", metric: 95.9 },
    { nome: "Austrália", metric: 95.8 },
    { nome: "Países Baixos", metric: 95.5 },
    { nome: "Irlanda", metric: 94.9 },
    { nome: "Singapura", metric: 94.6 },
    { nome: "Reino Unido", metric: 94.6 },
    { nome: "Emirados Árabes Unidos", metric: 94.0 },
    { nome: "Canadá", metric: 93.9 },
    { nome: "Nova Zelândia", metric: 93.8 },
    { nome: "Estados Unidos", metric: 93.8 },
    { nome: "Coreia do Sul", metric: 93.7 },
    { nome: "Japão", metric: 92.5 },
    { nome: "França", metric: 92.0 },
    { nome: "Israel", metric: 91.9 },
    { nome: "Espanha", metric: 91.8 },
    { nome: "Itália", metric: 91.5 },
    { nome: "Grécia", metric: 90.8 },
    { nome: "Polônia", metric: 90.6 },
    { nome: "Arábia Saudita", metric: 90.0 },
    { nome: "Portugal", metric: 89.0 },
    { nome: "Catar", metric: 88.6 },
    { nome: "Chile", metric: 87.8 },
    { nome: "Argentina", metric: 86.5 },
    { nome: "Uruguai", metric: 86.2 },
    { nome: "Turquia", metric: 85.3 },
    { nome: "Kuwait", metric: 85.2 },
    { nome: "Panamá", metric: 83.9 },
    { nome: "Rússia", metric: 83.2 },
    { nome: "Malásia", metric: 81.9 },
    { nome: "Bósnia e Herzegovina", metric: 80.4 },
    { nome: "Irã", metric: 79.9 },
    { nome: "China", metric: 79.7 },
    { nome: "Peru", metric: 79.4 },
    { nome: "México", metric: 78.9 },
    { nome: "Brasil", metric: 78.6 },
    { nome: "Ucrânia", metric: 77.9 },
    { nome: "Sri Lanka", metric: 77.6 },
    { nome: "Vietnã", metric: 76.6 },
    { nome: "Argélia", metric: 76.3 },
    { nome: "Cuba", metric: 76.2 },
    { nome: "Egito", metric: 75.4 },
    { nome: "Jordânia", metric: 75.4 },
    { nome: "Tunísia", metric: 74.6 },
    { nome: "África do Sul", metric: 74.1 },
    { nome: "Indonésia", metric: 72.8 },
    { nome: "Filipinas", metric: 72.0 },
    { nome: "Marrocos", metric: 71.0 },
    { nome: "Venezuela", metric: 70.9 },
    { nome: "Butão", metric: 69.8 },
    { nome: "Iraque", metric: 69.5 },
    { nome: "Bangladesh", metric: 68.5 },
    { nome: "Índia", metric: 68.5 },
    { nome: "Guatemala", metric: 66.2 },
    { nome: "Gana", metric: 62.8 },
    { nome: "Quênia", metric: 62.8 },
    { nome: "Nepal", metric: 62.2 },
    { nome: "Angola", metric: 61.6 },
    { nome: "Myanmar", metric: 60.9 },
    { nome: "Zimbábue", metric: 59.8 },
    { nome: "Zâmbia", metric: 59.5 },
    { nome: "Camarões", metric: 58.8 },
    { nome: "Uganda", metric: 58.2 },
    { nome: "Ruanda", metric: 57.8 },
    { nome: "Togo", metric: 57.1 },
    { nome: "Nigéria", metric: 56.0 },
    { nome: "Haiti", metric: 55.4 },
    { nome: "Lesoto", metric: 55.0 },
    { nome: "Paquistão", metric: 54.4 },
    { nome: "Senegal", metric: 53.0 },
    { nome: "República Democrática do Congo", metric: 52.2 },
    { nome: "Benin", metric: 51.5 },
    { nome: "Sudão", metric: 51.1 },
    { nome: "Guiné", metric: 50.0 },
    { nome: "Etiópia", metric: 49.7 },
    { nome: "Afeganistão", metric: 49.6 },
    { nome: "Madagascar", metric: 48.7 },
    { nome: "Iêmen", metric: 47.0 },
    { nome: "Serra Leoa", metric: 46.7 },
    { nome: "Burundi", metric: 43.9 },
    { nome: "Mali", metric: 41.9 },
    { nome: "Níger", metric: 41.9 },
    { nome: "Chade", metric: 41.6 },
    { nome: "República Centro-Africana", metric: 41.4 },
    { nome: "Somália", metric: 40.4 },
    { nome: "Sudão do Sul", metric: 38.8 },
    // --- expansão 2026-09-20 (+25) ---
    { nome: "Dinamarca", metric: 96.2 },
    { nome: "Suécia", metric: 95.9 },
    { nome: "Bélgica", metric: 95.1 },
    { nome: "Finlândia", metric: 94.8 },
    { nome: "Áustria", metric: 93.0 },
    { nome: "República Tcheca", metric: 91.5 },
    { nome: "Croácia", metric: 88.9 },
    { nome: "Hungria", metric: 87.0 },
    { nome: "Sérvia", metric: 83.3 },
    { nome: "Costa Rica", metric: 83.3 },
    { nome: "Tailândia", metric: 79.8 },
    { nome: "Colômbia", metric: 78.8 },
    { nome: "Equador", metric: 77.7 },
    { nome: "República Dominicana", metric: 77.6 },
    { nome: "Paraguai", metric: 75.6 },
    { nome: "Bolívia", metric: 73.3 },
    { nome: "Suriname", metric: 72.2 },
    { nome: "Jamaica", metric: 72.0 },
    { nome: "El Salvador", metric: 67.8 },
    { nome: "Cabo Verde", metric: 66.8 },
    { nome: "Honduras", metric: 64.5 },
    { nome: "São Tomé e Príncipe", metric: 63.7 },
    { nome: "Timor-Leste", metric: 63.4 },
    { nome: "Guiné-Bissau", metric: 51.4 },
    { nome: "Moçambique", metric: 49.3 },
  ],
  esportes: [
    // Índice de popularidade global estimado (0-100, futebol como referência ~100), cruzando múltiplas fontes
    { nome: "Futebol", metric: 100.0 },
    { nome: "Críquete", metric: 67.6 },
    { nome: "Basquete", metric: 59.5 },
    { nome: "Hóquei sobre Grama", metric: 54.1 },
    { nome: "Tênis", metric: 27.0 },
    { nome: "Vôlei", metric: 24.3 },
    { nome: "Tênis de Mesa", metric: 23.2 },
    { nome: "Xadrez", metric: 16.2 },
    { nome: "Beisebol", metric: 13.5 },
    { nome: "Rugby", metric: 11.4 },
    { nome: "Futebol Americano", metric: 10.8 },
    { nome: "E-Sports", metric: 10.7 },
    { nome: "Golfe", metric: 10.5 },
    { nome: "Fórmula 1", metric: 9.5 },
    { nome: "Motociclismo (MotoGP)", metric: 8.6 },
    { nome: "Badminton", metric: 7.6 },
    { nome: "Boxe", metric: 7.3 },
    { nome: "Atletismo", metric: 7.0 },
    { nome: "Hóquei no Gelo", metric: 6.8 },
    { nome: "Handebol", metric: 6.2 },
    { nome: "Ciclismo", metric: 5.7 },
    { nome: "Natação", metric: 5.3 },
    { nome: "MMA (Artes Marciais Mistas)", metric: 4.9 },
    { nome: "Kabaddi", metric: 4.1 },
    { nome: "Ginástica", metric: 3.9 },
    { nome: "Sinuca", metric: 3.8 },
    { nome: "Luta Olímpica", metric: 3.2 },
    { nome: "Boliche", metric: 2.7 },
    { nome: "Dardos", metric: 2.4 },
    { nome: "Surfe", metric: 1.9 },
    { nome: "Skate", metric: 1.8 },
    { nome: "Netball", metric: 1.6 },
    { nome: "Lacrosse", metric: 1.5 },
    { nome: "Halterofilismo", metric: 1.4 },
    { nome: "Patinação Artística no Gelo", metric: 1.2 },
    { nome: "Remo", metric: 1.1 },
    { nome: "Polo Aquático", metric: 1.1 },
    { nome: "Vela", metric: 1.0 },
    { nome: "Judô", metric: 0.9 },
    { nome: "Taekwondo", metric: 0.9 },
    { nome: "Canoagem/Caiaque", metric: 0.8 },
    { nome: "Caratê", metric: 0.7 },
    { nome: "Esgrima", metric: 0.7 },
    { nome: "Hipismo", metric: 0.7 },
    { nome: "Tiro com Arco", metric: 0.6 },
    { nome: "Squash", metric: 0.6 },
    { nome: "Triatlo", metric: 0.5 },
    { nome: "Pentatlo Moderno", metric: 0.5 },
    { nome: "Sumô", metric: 0.4 },
    { nome: "Curling", metric: 0.4 },
    { nome: "Escalada Esportiva", metric: 0.4 },
    { nome: "Frisbee (Ultimate)", metric: 0.3 },
    { nome: "Pólo (Equestre)", metric: 0.3 },
    { nome: "Sepak Takraw", metric: 0.2 },
    { nome: "Hurling", metric: 0.2 },
    { nome: "Bandy", metric: 0.1 },
    // --- expansão 2026-09-20 (+18) ---
    { nome: "Automobilismo (NASCAR/Stock Car)", metric: 3.5 },
    { nome: "Futsal", metric: 3.4 },
    { nome: "Luta Livre Profissional (WWE)", metric: 2.8 },
    { nome: "Vôlei de Praia", metric: 2.2 },
    { nome: "Esqui Alpino", metric: 1.6 },
    { nome: "Padel", metric: 1.5 },
    { nome: "Jiu-Jitsu Brasileiro", metric: 1.3 },
    { nome: "Muay Thai", metric: 1.2 },
    { nome: "Kickboxing", metric: 1.1 },
    { nome: "Motocross", metric: 1 },
    { nome: "Snowboard", metric: 0.9 },
    { nome: "Fisiculturismo", metric: 0.8 },
    { nome: "Saltos Ornamentais", metric: 0.7 },
    { nome: "Capoeira", metric: 0.6 },
    { nome: "Bocha", metric: 0.5 },
    { nome: "Beach Tennis", metric: 0.4 },
    { nome: "Futevôlei", metric: 0.3 },
    { nome: "Peteca", metric: 0.1 },
  ],
  albuns: [
    // Metascore do Metacritic Music (ou equivalente agregado quando não coberto)
    { nome: "Abbey Road — The Beatles", metric: 95.0 },
    { nome: "The Dark Side of the Moon — Pink Floyd", metric: 96.0 },
    { nome: "Rumours — Fleetwood Mac", metric: 90.0 },
    { nome: "Exile on Main St. — The Rolling Stones", metric: 91.0 },
    { nome: "OK Computer — Radiohead", metric: 95.0 },
    { nome: "Nevermind — Nirvana", metric: 92.0 },
    { nome: "In Rainbows — Radiohead", metric: 88.0 },
    { nome: "Is This It — The Strokes", metric: 91.0 },
    { nome: "Elephant — The White Stripes", metric: 92.0 },
    { nome: "Funeral — Arcade Fire", metric: 90.0 },
    { nome: "Fetch the Bolt Cutters — Fiona Apple", metric: 98.0 },
    { nome: "Currents — Tame Impala", metric: 84.0 },
    { nome: "AM — Arctic Monkeys", metric: 81.0 },
    { nome: "Boxer — The National", metric: 70.0 },
    { nome: "MAGDALENE — FKA twigs", metric: 88.0 },
    { nome: "Babel — Mumford & Sons", metric: 63.0 },
    { nome: "American Idiot — Green Day", metric: 84.0 },
    { nome: "Chinese Democracy — Guns N' Roses", metric: 71.0 },
    { nome: "Death Magnetic — Metallica", metric: 78.0 },
    { nome: "We Are Not Your Kind — Slipknot", metric: 93.0 },
    { nome: "Crack the Skye — Mastodon", metric: 82.0 },
    { nome: "White Pony — Deftones", metric: 84.0 },
    { nome: "Random Access Memories — Daft Punk", metric: 87.0 },
    { nome: "Mezzanine — Massive Attack", metric: 87.0 },
    { nome: "Dummy — Portishead", metric: 92.0 },
    { nome: "To Pimp a Butterfly — Kendrick Lamar", metric: 96.0 },
    { nome: "DAMN. — Kendrick Lamar", metric: 95.0 },
    { nome: "good kid, m.A.A.d city — Kendrick Lamar", metric: 91.0 },
    { nome: "Mr. Morale & the Big Steppers — Kendrick Lamar", metric: 85.0 },
    { nome: "Stankonia — OutKast", metric: 95.0 },
    { nome: "Madvillainy — Madvillain", metric: 93.0 },
    { nome: "My Beautiful Dark Twisted Fantasy — Kanye West", metric: 94.0 },
    { nome: "Yeezus — Kanye West", metric: 84.0 },
    { nome: "The Life of Pablo — Kanye West", metric: 75.0 },
    { nome: "Views — Drake", metric: 69.0 },
    { nome: "Coloring Book — Chance the Rapper", metric: 89.0 },
    { nome: "Astroworld — Travis Scott", metric: 85.0 },
    { nome: "Black Messiah — D'Angelo and the Vanguard", metric: 95.0 },
    { nome: "Channel Orange — Frank Ocean", metric: 91.0 },
    { nome: "Blonde — Frank Ocean", metric: 87.0 },
    { nome: "CTRL — SZA", metric: 87.0 },
    { nome: "SOS — SZA", metric: 94.0 },
    { nome: "A Seat at the Table — Solange", metric: 89.0 },
    { nome: "Back to Black — Amy Winehouse", metric: 81.0 },
    { nome: "What's Going On — Marvin Gaye", metric: 96.0 },
    { nome: "Thriller — Michael Jackson", metric: 92.0 },
    { nome: "Lemonade — Beyoncé", metric: 92.0 },
    { nome: "Renaissance — Beyoncé", metric: 91.0 },
    { nome: "COWBOY CARTER — Beyoncé", metric: 91.0 },
    { nome: "folklore — Taylor Swift", metric: 88.0 },
    { nome: "Happier Than Ever — Billie Eilish", metric: 88.0 },
    { nome: "When We All Fall Asleep, Where Do We Go? — Billie Eilish", metric: 82.0 },
    { nome: "21 — Adele", metric: 76.0 },
    { nome: "Norman Fucking Rockwell! — Lana Del Rey", metric: 87.0 },
    { nome: "Melodrama — Lorde", metric: 91.0 },
    { nome: "GUTS — Olivia Rodrigo", metric: 91.0 },
    { nome: "÷ (Divide) — Ed Sheeran", metric: 64.0 },
    { nome: "Purple Rain — Prince and the Revolution", metric: 91.0 },
    { nome: "Anti — Rihanna", metric: 73.0 },
    { nome: "After Hours — The Weeknd", metric: 80.0 },
    { nome: "Illinois — Sufjan Stevens", metric: 90.0 },
    { nome: "Punisher — Phoebe Bridgers", metric: 90.0 },
    { nome: "Sobrevivendo no Inferno — Racionais MC's", metric: 85.0 },
    { nome: "Construção — Chico Buarque", metric: 86.0 },
    { nome: "Expresso 2222 — Gilberto Gil", metric: 80.0 },
    { nome: "Refazenda — Gilberto Gil", metric: 77.0 },
    { nome: "Elis & Tom — Elis Regina & Antônio Carlos Jobim", metric: 79.0 },
    { nome: "Caetano Veloso (Tropicália) — Caetano Veloso", metric: 81.0 },
    { nome: "Os Mutantes — Os Mutantes", metric: 78.0 },
    { nome: "Dois — Legião Urbana", metric: 65.0 },
    { nome: "Tim Maia — Tim Maia", metric: 76.0 },
    { nome: "Verdade, uma Ilusão — Marisa Monte", metric: 72.0 },
    { nome: "Bluesman — Baco Exu do Blues", metric: 74.0 },
    { nome: "Alumbramento — Djavan", metric: 76.0 },
    { nome: "África Brasil — Jorge Ben", metric: 85.0 },
    { nome: "Acabou Chorare — Novos Baianos", metric: 91.0 },
    { nome: "Da Lama ao Caos — Chico Science & Nação Zumbi", metric: 82.0 },
    { nome: "Elis — Elis Regina", metric: 82.0 },
    // --- expansão 2026-09-20 (+30) ---
    { nome: "AmarElo — Emicida", metric: 82 },
    { nome: "Nó na Orelha — Criolo", metric: 78 },
    { nome: "As Quatro Estações — Legião Urbana", metric: 79 },
    { nome: "Cabeça Dinossauro — Titãs", metric: 80 },
    { nome: "Roots — Sepultura", metric: 72 },
    { nome: "Ideologia — Cazuza", metric: 66 },
    { nome: "Racional Vol. 1 — Tim Maia", metric: 88 },
    { nome: "A Tábua de Esmeralda — Jorge Ben", metric: 90 },
    { nome: "Afrociberdelia — Chico Science & Nação Zumbi", metric: 79 },
    { nome: "Numanice #2 — Ludmilla", metric: 58 },
    { nome: "Batidão Tropical — Pabllo Vittar", metric: 62 },
    { nome: "333 — Matuê", metric: 55 },
    { nome: "Admirável Chip Novo — Pitty", metric: 67 },
    { nome: "Lado B Lado A — O Rappa", metric: 74 },
    { nome: "Transpiração Contínua Prolongada — Charlie Brown Jr.", metric: 63 },
    { nome: "Versions of Me — Anitta", metric: 78 },
    { nome: "Debí Tirar Más Fotos — Bad Bunny", metric: 95 },
    { nome: "Future Nostalgia — Dua Lipa", metric: 88 },
    { nome: "The Blueprint — Jay-Z", metric: 88 },
    { nome: "Led Zeppelin IV — Led Zeppelin", metric: 100 },
    { nome: "Invincible — Michael Jackson", metric: 51 },
    { nome: "Music of the Spheres — Coldplay", metric: 55 },
    { nome: "One More Light — Linkin Park", metric: 46 },
    { nome: "Be Here Now — Oasis", metric: 57 },
    { nome: "Donda — Kanye West", metric: 53 },
    { nome: "Mayhem — Lady Gaga", metric: 84 },
    { nome: "The Marshall Mathers LP — Eminem", metric: 78 },
    { nome: "Illmatic — Nas", metric: 89 },
    { nome: "Proof — BTS", metric: 88 },
    { nome: "In Utero — Nirvana", metric: 90 },
  ],
  herois: [
    // "Índice de Poder" — estimativa curada por consenso de tier lists (não é métrica oficial única)
    { nome: "A Presença (DC)", metric: 99.5 },
    { nome: "Doutor Manhattan", metric: 97.5 },
    { nome: "Zeno (Dragon Ball)", metric: 97.0 },
    { nome: "Saitama (One Punch Man)", metric: 96.0 },
    { nome: "Galactus", metric: 95.0 },
    { nome: "Goku (Dragon Ball)", metric: 94.0 },
    { nome: "Espectro (DC)", metric: 93.0 },
    { nome: "Darkseid", metric: 92.0 },
    { nome: "Kaguya Otsutsuki (Naruto)", metric: 91.5 },
    { nome: "Feiticeira Escarlate", metric: 91.0 },
    { nome: "Thanos", metric: 90.0 },
    { nome: "Jean Grey (Fênix Negra)", metric: 89.5 },
    { nome: "Vegeta (Dragon Ball)", metric: 89.0 },
    { nome: "Beerus (Dragon Ball)", metric: 88.5 },
    { nome: "Superman", metric: 88.0 },
    { nome: "Odin", metric: 87.5 },
    { nome: "Madara Uchiha (Naruto)", metric: 87.0 },
    { nome: "Doomsday", metric: 86.5 },
    { nome: "Sentry", metric: 86.0 },
    { nome: "Monkey D. Luffy (One Piece)", metric: 85.5 },
    { nome: "Caçador Marciano", metric: 85.0 },
    { nome: "Gojo Satoru (Jujutsu Kaisen)", metric: 84.5 },
    { nome: "Surfista Prateado", metric: 84.0 },
    { nome: "Naruto Uzumaki", metric: 83.5 },
    { nome: "Sasuke Uchiha", metric: 83.0 },
    { nome: "Flash (Barry Allen)", metric: 82.5 },
    { nome: "Capitã Marvel", metric: 82.0 },
    { nome: "Mulher Maravilha", metric: 81.5 },
    { nome: "Thor", metric: 81.0 },
    { nome: "Eren Yeager (Ataque dos Titãs)", metric: 80.0 },
    { nome: "Poseidon (Cavaleiros do Zodíaco)", metric: 79.5 },
    { nome: "Apocalipse", metric: 79.0 },
    { nome: "All For One (My Hero Academia)", metric: 78.0 },
    { nome: "Hulk", metric: 77.5 },
    { nome: "Doutor Destino", metric: 77.0 },
    { nome: "Omni-Man (Invincible)", metric: 76.5 },
    { nome: "All Might", metric: 76.0 },
    { nome: "Doutor Estranho", metric: 75.5 },
    { nome: "Homelander (The Boys)", metric: 75.0 },
    { nome: "Shazam", metric: 74.0 },
    { nome: "Magneto", metric: 73.0 },
    { nome: "Invincible (Mark Grayson)", metric: 72.0 },
    { nome: "Doutor Fado", metric: 71.5 },
    { nome: "Lanterna Verde (Hal Jordan)", metric: 71.0 },
    { nome: "Tempestade", metric: 70.0 },
    { nome: "Aquaman", metric: 68.0 },
    { nome: "Ciborgue", metric: 66.0 },
    { nome: "Visão", metric: 65.0 },
    { nome: "Tanjiro Kamado (Demon Slayer)", metric: 63.0 },
    { nome: "Loki", metric: 62.0 },
    { nome: "Homem de Ferro", metric: 61.0 },
    { nome: "Zatanna", metric: 60.0 },
    { nome: "Mulher-Hulk", metric: 59.0 },
    { nome: "Wolverine", metric: 58.0 },
    { nome: "Seiya de Pégaso (Cavaleiros do Zodíaco)", metric: 57.0 },
    { nome: "Pantera Negra", metric: 56.0 },
    { nome: "Venom", metric: 55.0 },
    { nome: "Deadpool", metric: 54.0 },
    { nome: "Genos (One Punch Man)", metric: 53.0 },
    { nome: "Robin (Damian Wayne)", metric: 45.0 },
    { nome: "Capitão América", metric: 44.0 },
    { nome: "Homem-Aranha", metric: 42.0 },
    { nome: "Levi Ackerman (Ataque dos Titãs)", metric: 39.0 },
    { nome: "Asa Noturna", metric: 38.0 },
    { nome: "Homem-Formiga", metric: 37.0 },
    { nome: "Batman", metric: 36.0 },
    { nome: "Cavaleiro da Lua", metric: 34.0 },
    { nome: "Soldado Invernal", metric: 33.0 },
    { nome: "Demolidor", metric: 30.0 },
    { nome: "Arqueiro Verde", metric: 29.0 },
    { nome: "John Constantine", metric: 28.0 },
    { nome: "Bullseye", metric: 27.0 },
    { nome: "Lex Luthor", metric: 26.0 },
    { nome: "Rei do Crime (Kingpin)", metric: 25.0 },
    { nome: "Gavião Arqueiro", metric: 24.0 },
    { nome: "Viúva Negra", metric: 22.0 },
    { nome: "Justiceiro", metric: 21.0 },
    { nome: "Coringa", metric: 19.0 },
    { nome: "Mulher-Gato", metric: 17.0 },
    { nome: "Harley Quinn", metric: 16.0 },
    { nome: "Light Yagami (Death Note)", metric: 14.0 },
    { nome: "Vigilante (DC)", metric: 12.0 },
    // --- expansão 2026-09-20 (+30) ---
    { nome: "Broly (Dragon Ball)", metric: 90 },
    { nome: "Kirby", metric: 89 },
    { nome: "Freeza (Dragon Ball)", metric: 86 },
    { nome: "Kratos (God of War)", metric: 85 },
    { nome: "Sukuna (Jujutsu Kaisen)", metric: 84 },
    { nome: "Sauron", metric: 83 },
    { nome: "Godzilla", metric: 82 },
    { nome: "Mob (Mob Psycho 100)", metric: 81 },
    { nome: "Ichigo Kurosaki (Bleach)", metric: 80.5 },
    { nome: "Adão Negro", metric: 80 },
    { nome: "Spawn", metric: 79 },
    { nome: "Mewtwo", metric: 78 },
    { nome: "Ultron", metric: 77.5 },
    { nome: "Gandalf", metric: 72 },
    { nome: "Imperador Palpatine", metric: 68 },
    { nome: "Sonic", metric: 66 },
    { nome: "Yoda", metric: 64 },
    { nome: "Jotaro Kujo (JoJo)", metric: 62 },
    { nome: "Darth Vader", metric: 60 },
    { nome: "Shun de Andrômeda (Cavaleiros do Zodíaco)", metric: 58 },
    { nome: "Lord Voldemort", metric: 52 },
    { nome: "Mario", metric: 48 },
    { nome: "Edward Elric (Fullmetal Alchemist)", metric: 47 },
    { nome: "Master Chief (Halo)", metric: 40 },
    { nome: "Pikachu", metric: 35 },
    { nome: "Bane", metric: 31 },
    { nome: "Duende Verde", metric: 30 },
    { nome: "Doutor Octopus", metric: 29 },
    { nome: "Ra's al Ghul", metric: 27.5 },
    { nome: "Chapolin Colorado", metric: 9 },
  ],
  desenhos: [
    // Nota IMDb (0-10). Desenhos e programas infantis que marcaram gerações no
    // Brasil (TV Globinho, TV Cultura, SBT, Cartoon Network/Nickelodeon Brasil).
    { nome: "Super Choque", metric: 7.4 },
    { nome: "Bob Esponja Calça Quadrada", metric: 8.2 },
    { nome: "Clube das Winx", metric: 6.4 },
    { nome: "Juniper Lee", metric: 6.5 },
    { nome: "Phineas e Ferb", metric: 8.1 },
    { nome: "X-Men: Evolution", metric: 7.8 },
    { nome: "Peixonauta", metric: 6.8 },
    { nome: "George, o Curioso", metric: 7.2 },
    { nome: "Mister Maker", metric: 8.1 },
    { nome: "Pinky Dinky Doo", metric: 6.4 },
    { nome: "Princesas do Mar", metric: 5.4 },
    { nome: "Padrinhos Mágicos", metric: 7.2 },
    { nome: "Ben 10", metric: 7.6 },
    { nome: "Liga da Justiça: A Série Animada", metric: 8.5 },
    { nome: "Cocoricó", metric: 7.4 },
    { nome: "Três Espiãs Demais", metric: 7.1 },
    { nome: "Jake Long: O Dragão Americano", metric: 6.6 },
    { nome: "As Aventuras de Jackie Chan", metric: 7.4 },
    { nome: "Super Onze", metric: 8.2 },
    { nome: "Os Flintstones", metric: 7.5 },
    { nome: "Projeto Zeta", metric: 6.9 },
    { nome: "Manda-Chuva", metric: 7.1 },
    { nome: "Scooby-Doo", metric: 7.4 },
    { nome: "As Meninas Superpoderosas", metric: 7.3 },
    { nome: "Coragem, o Cão Covarde", metric: 8.3 },
    { nome: "Chaves", metric: 8.7 },
    { nome: "Chapolin", metric: 8.5 },
    { nome: "Os Simpsons", metric: 8.6 },
    { nome: "Três É Demais", metric: 6.8 },
    { nome: "Arnold", metric: 7.6 },
    { nome: "Kid vs. Kat", metric: 6.2 },
    { nome: "Um Maluco no Pedaço", metric: 7.9 },
    { nome: "Eu, a Patroa e as Crianças", metric: 7.0 },
    { nome: "Pica-Pau", metric: 7.0 },
    { nome: "Tom e Jerry", metric: 8.2 },
    { nome: "The Garfield Show", metric: 5.8 },
    { nome: "Pinky e o Cérebro", metric: 7.8 },
    { nome: "O Laboratório de Dexter", metric: 7.8 },
    { nome: "O Incrível Mundo de Gumball", metric: 8.8 },
    { nome: "Apenas um Show", metric: 8.6 },
    { nome: "Os Jovens Titãs", metric: 7.9 },
    { nome: "Os Jovens Titãs em Ação", metric: 5.8 },
    { nome: "Mecanimais", metric: 6.2 },
    { nome: "Os Carrinhos", metric: 1.9 },
    { nome: "A Mansão Foster para Amigos Imaginários", metric: 7.5 },
    { nome: "O Espetacular Homem-Aranha", metric: 8.4 },
    { nome: "Pantera Cor de Rosa", metric: 7.6 },
    { nome: "O Máskara", metric: 6.9 },
    { nome: "As Terríveis Aventuras de Billy e Mandy", metric: 7.6 },
    { nome: "The Batman", metric: 7.4 },
    { nome: "South Park", metric: 8.7 },
    { nome: "Drama Total", metric: 7.3 },
    { nome: "Corrida Maluca", metric: 7.5 },
    { nome: "Clifford, O Grande Cão Vermelho", metric: 6.5 },
    { nome: "A Turma da Mônica", metric: 8.2 },
    { nome: "Backyardigans", metric: 7.2 },
    { nome: "Hora de Aventura", metric: 8.7 },
    { nome: "Samurai Jack", metric: 8.5 },
    { nome: "As Visões da Raven", metric: 6.6 },
    { nome: "Scooby-Doo, Cadê Você?", metric: 7.9 },
    { nome: "Rick and Morty", metric: 9.0 },
    { nome: "Kick Buttowski: Um Projeto de Dublê", metric: 6.8 },
    { nome: "Gravity Falls: Um Verão de Mistérios", metric: 8.9 },
    { nome: "Futebol de Rua", metric: 7.8 },
    { nome: "Death Note", metric: 8.9 },
    { nome: "Zack & Cody: Gêmeos em Ação", metric: 6.6 },
    { nome: "Agente K.C.", metric: 6.5 },
    { nome: "Oscar no Oásis", metric: 7.3 },
    { nome: "As Aventuras de Flapjack", metric: 7.8 },
    { nome: "iCarly", metric: 6.8 },
    { nome: "Drake & Josh", metric: 7.7 },
    { nome: "Boa Sorte, Charlie", metric: 7.1 },
    { nome: "Jessie", metric: 6.1 },
    { nome: "Big Time Rush", metric: 6.6 },
    { nome: "Zé Colmeia", metric: 6.6 },
    { nome: "Sr. Young", metric: 6.0 },
    { nome: "No Ritmo", metric: 5.1 },
    { nome: "Os Feiticeiros de Waverly Place", metric: 6.9 },
    { nome: "Fanboy e Chum Chum", metric: 3.5 },
    { nome: "Austin & Ally", metric: 6.1 },
    { nome: "Sam & Cat", metric: 5.8 },
    { nome: "Brilhante Vitória", metric: 7.0 },
    { nome: "Lazy Town", metric: 6.0 },
    { nome: "As Aventuras com os Kratts", metric: 7.7 },
    { nome: "Meu Amigãozão", metric: 7.3 },
    { nome: "As Aventuras de Elliot", metric: 4.7 },
    { nome: "Kenan e Kel", metric: 8.4 },
    { nome: "Sid, O Cientista", metric: 5.5 },
    { nome: "Pocoyo", metric: 7.1 },
    { nome: "Thomas e Seus Amigos", metric: 6.5 },
    { nome: "Looney Tunes", metric: 7.8 },
    { nome: "Osmar", metric: 7.5 },
    { nome: "Os Jetsons", metric: 7.0 },
    // --- clássicos extras que marcaram época na TV brasileira ---
    { nome: "He-Man e os Mestres do Universo", metric: 7.5 },
    { nome: "Thundercats", metric: 7.9 },
    { nome: "Caverna do Dragão", metric: 7.9 },
    { nome: "Os Smurfs", metric: 7.2 },
    { nome: "Ursinhos Carinhosos", metric: 7.0 },
    { nome: "Popeye, o Marinheiro", metric: 7.0 },
    { nome: "Alvin e os Esquilos", metric: 7.6 },
    { nome: "Voltron", metric: 8.0 },
    { nome: "Comandos em Ação", metric: 7.5 },
    { nome: "Transformers (Geração 1)", metric: 8.0 },
    { nome: "Inspetor Bugiganga", metric: 6.8 },
    { nome: "Denver, o Último Dinossauro", metric: 6.4 },
    { nome: "Capitão Planeta", metric: 6.0 },
    { nome: "Tiny Toon: Aventuras Malucas", metric: 7.5 },
    { nome: "Animaniacs", metric: 7.8 },
    { nome: "She-Ra: A Princesa do Poder", metric: 6.6 },
    { nome: "Os Caça-Fantasmas", metric: 7.5 },
    { nome: "Jem e as Hologramas", metric: 6.8 },
    { nome: "Os Snorks", metric: 6.4 },
    { nome: "DuckTales: Os Caçadores de Aventuras", metric: 7.9 },
    { nome: "Chip 'n Dale: Os Defensores da Lei", metric: 7.6 },
    { nome: "TaleSpin: Tal e Qual", metric: 7.5 },
    { nome: "Darkwing Duck: O Pato Negro", metric: 7.4 },
    { nome: "Recess: A Turma do Recreio", metric: 7.6 },
    { nome: "Rugrats: Os Anjinhos", metric: 7.3 },
    { nome: "Doug", metric: 7.4 },
    { nome: "CatDog: Gato e Cachorro", metric: 6.5 },
    { nome: "Ren & Stimpy", metric: 7.5 },
    { nome: "Sítio do Picapau Amarelo", metric: 6.8 },
    { nome: "Castelo Rá-Tim-Bum", metric: 8.8 },
    { nome: "Mundo da Lua", metric: 7.4 },
    { nome: "Vila Sésamo", metric: 7.0 },
    { nome: "TV Colosso", metric: 7.5 },
    { nome: "Cavaleiros do Zodíaco", metric: 8.4 },
    { nome: "Yu Yu Hakusho", metric: 8.4 },
    { nome: "Sakura Card Captors", metric: 8.0 },
    { nome: "Digimon", metric: 7.4 },
    { nome: "Pokémon", metric: 7.6 },
    { nome: "Dragon Ball Z", metric: 8.7 },
    { nome: "Naruto", metric: 8.4 },
    { nome: "Yu-Gi-Oh!", metric: 7.7 },
    { nome: "One Piece", metric: 9.0 },
    { nome: "InuYasha", metric: 7.9 },
    { nome: "Shaman King", metric: 8.0 },
    { nome: "Meteoro", metric: 7.2 },
    { nome: "Heidi", metric: 7.5 },
  ],
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = { DADOS_VERSAO, TEMAS_META, DADOS_PADRAO };
}
